### ISSUE TITLE
Kuskus markdown syntax highlighting messes up markdown highlighting outside code block

### ISSUE THREAD

**Issue by o-l-a-v** [rosshamish/kuskus#122]
|Product |Version
|:--|:--
|VSCode |v1.86.2
|[Kuskus] Kusto Syntax Highlighting |v1.2.0

Kuskus markdown syntax highlighting messes up markdown highlighting even outside the code block.

## Sample markdown code

````markdown
# Test

## First query

```kql
SomeTable
| top 10 by TimeGenerated desc
```

## Second query

```kql
SomeTable
| top 10 by TimeGenerated desc
```

## Third query

```kql
SomeTable
| top 10 by TimeGenerated desc
```
````

## Result in VSCode

<img width="446" alt="image" src="https://github.com/rosshamish/kuskus/assets/6450056/0ac5165b-ad4b-4d2e-8732-04a9da15a8fd">

Seems it alternates too. So all text under an odd number of kql / kusto code blocks does not get proper regular markdown highlighting.

If you change codeblock to something else like sql instead, highlighted markdown outside a codeblock is not affected:

<img width="448" alt="image" src="https://github.com/rosshamish/kuskus/assets/6450056/0f178082-5c59-4eac-b080-881a57b3a9a5">

**Comment by rosshamish** [comment]
Interesting. Appreciate the info and quality repro. FYI, I'm not maintaining this extension much lately but I'm happy to field a bug report and also review a PR if you're interested to take a stab at a fix.

**Comment by rosshamish** [comment]
Looks like #112 is the PR which added the markdown highlighting -- if you're interested (or anyone else reading this), feel free to take a peek in there and see if you can't find the bug

**Comment by rosshamish** [comment]
@Caleb-Wishart might have some ideas too since they implemented the markdown support a while back

**Comment by Caleb-Wishart** [comment]
I'll see if I can find some time to take a look

**Comment by o-l-a-v** [comment]
It maybe got something to do with the regex in here?

* <https://github.com/rosshamish/kuskus/blob/master/kusto-syntax-highlighting/syntaxes/kusto-markdown-codeblock.json>

Inspiration:

* LaTeX-Workshop: <https://github.com/James-Yu/LaTeX-Workshop/blob/master/syntax/markdown-latex-combined.tmLanguage.json>
* vscode-fenced-code-block-grammar-injection-example: <https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example/blob/master/syntaxes/codeblock.json>

**Comment by o-l-a-v** [comment]
A PR is up @rosshamish. :)

**Comment by Caleb-Wishart** [comment]
Nice!
I just picked that regex off another tutorial. Must have been out of date

**Comment by rosshamish** [comment]
Deploying now W/ https://github.com/rosshamish/kuskus/actions/runs/8039305015
