### ISSUE TITLE
Coloring fails to recognize escaping backslash characters from escaping other special characters

### ISSUE THREAD

**Issue by asilverman** [rosshamish/kuskus#159]
Consider the following query:

```kql
let scannerId = "9d632724-5c18-43e9-9314-555e9587b30c";
cluster("foo").database("bar").table("baz")
| extend ScannerName = tostring(todynamic(Properties).scannerConfigurationName)
| where Name matches regex "Skipping comment creation for file" and Name matches regex "as the scanner rule is in silent mode"
| extend FullFileName = extract("Skipping comment creation for file (. + ) as the scanner rule is in silent mode", 1, Name)
| extend FileNameParts = split(FullFileName, "Modified\\")
| extend FileName = iff(isempty(FileNameParts[1]), FullFileName, strcat("\\", FileNameParts[1])) //FullFileName was added on 2/2/24
| extend FileName = trim("'", FileName)
```

Notice how the github highlighting recognizes the line `| extend FileNameParts = split(FullFileName, "Modified\\")` to be escaping the backslash characted being escaped. However, the kuskus extension doesn't (as shown below)
![image](https://github.com/rosshamish/kuskus/assets/9611108/f91ece55-5311-4a6b-ad3e-4c6ea8e7b197)

## Version Information:

![image](https://github.com/rosshamish/kuskus/assets/9611108/062ea4a5-58e7-43d1-b7ac-5e8c9c8737c1)

**Comment by rosshamish** [comment]
Good bug, thanks for the report. 

If you (or anyone reading) is willing to put a fix together, I'd be happy to facilitate. There's some good test coverage for the syntax highlighting, so it would be "as simple" as adding a new test case to cover this scenario, then updating the syntax highlighting regex to make the new test pass.

**Comment by rosshamish** [comment]
Found some time to look at this - fixed in #162 , published as v2.0.2 in https://github.com/rosshamish/kuskus/actions/runs/9056796653/job/24879823341

**Comment by rosshamish** [comment]
@asilverman please take a look and see if you can verify the fix. Thanks!

**Comment by asilverman** [comment]
@rosshamish Im out in vacation, I'll try to take a look at it by May 28
