### ISSUE TITLE
Syntax Highlighting does not work

### ISSUE THREAD

**Issue by pejuborg** [rosshamish/kuskus#19]
Hi,
Installed the Kuskus pack, but I don't get the syntax highlighting I expect and can't fin any information on what I should do to make it work.
/Per

**Comment by TheCloudScout** [comment]
I'm having the same issue

**Comment by pejuborg** [comment]
Yes, you are correct @TheCloudScout it was the same for me, removed all extensions related to Kusto and only used the highlight one.
