### ISSUE TITLE
authentication trouble

### ISSUE THREAD

**Issue by stevenhurwitt** [rosshamish/kuskus#26]
i always have trouble authenticating with data explorer (web ui works, but kusto explorer does not), so it's def not specific to kuskus but is there any other way to authenticate? or maybe to choose a specific tenant id?

also i know nothing about vscode extensions or typescript but just wanted to say thanks for this! was disappointed there's no kusto extension in VS so this is nice. i'd like to learn enough to make an extension for kusto similar to mssql in VSCode or npgsql in VS, but who know...

**Comment by stevenhurwitt** [comment]
ok so i answered my own question: essentially kuskus is using .withAadDeviceAuthentication and i'm only able to authenticate using .withAadApplicationKeyAuthentication. so i'm going to attempt to either replace or add in this functionality (i don't know js/ts) and see if that works when i build the extension.

**Comment by stevenhurwitt** [comment]
Please see this pull request regarding my changes: https://github.com/rosshamish/kuskus/pull/27. If anyone happens to be reading this who also get auth errors with the "common" authority id feel free to use my fork that enables an authority/tenant id parameter.

**Comment by rosshamish** [comment]
> I'd like to learn enough to make an extension for kusto similar to mssql in VSCode or npgsql in VS, but who know...

Hey I mean, if you're interested in learning you're welcome to build an extension and once it reaches some level of stability we could bundle it into this extension pack. I won't be able to spend much time actively developing on this but I can definitely be around for discussion and reviews and such.

> Please see this pull request regarding my changes: #27. 

Reviewed and approved. Looks good! Thanks for the change!
