### ISSUE TITLE
Syntax highlighting doesn't work with certain color themes

### ISSUE THREAD

**Issue by RamenTurismo** [rosshamish/kuskus#43]
Here is with the current version of the extension : 

![image](https://user-images.githubusercontent.com/14222512/144273397-d0327884-c92a-4c4a-98f2-8e49e3becf73.png)

And with the base fork (Azure Log Analytics (Kusto) Syntax Highlighting) :

![image](https://user-images.githubusercontent.com/14222512/144273518-55ab8257-108b-436c-8a29-8751773220a8.png)

With one extension, almost nothing is supported, with another the keyword `has` is not supported.

**Comment by rosshamish** [comment]
Hey Ramen,

Could you try with a different color theme? Some themes don't support the textmate syntax categories used in this language pack. I recommend "[Kuskus] Kusto (Dark)" which is also available in this extension pack, or separately on its own.

Let me know if that helps at all.

-Ross

**Comment by RamenTurismo** [comment]
I test the following with different themes :

```
Logs
| where operation_Name has "Test"
| order by timestamp desc
```

Default dark theme & VS dark Theme :
![image](https://user-images.githubusercontent.com/14222512/144383462-30fb4f58-e27c-4f89-ba81-323fe355b73d.png)

Monokai
![image](https://user-images.githubusercontent.com/14222512/144383775-258eb2ca-a5d1-499d-9b0a-a7adac8dcedd.png)

I won't be posting the others, because it seems the only theme supported is the `Monokai` one, which is a bit sad.
Do you accept Pull Requests ? I could be looking into this.

**Comment by rosshamish** [comment]
Huh, strange. Ideally the syntax highlighting works with all popular themes.

I'd absolutely accept a pull request. It's a regular textmate syntax definition, the standard VS Code syntax docs are solid for this. Let me know any questions you have!

**Comment by rosshamish** [comment]
@RamenTurismo I'm able to repro your issue on my end. I had been using either "Monokai" or "[Kuskus] Kusto (Dark)" theme for kusto work for a long time, so didn't notice. Thanks for the report!

I've added some testing support for the syntax highlighting, and wrote some info in the README on how to use it. Feel free to leverage that: https://github.com/rosshamish/kuskus/tree/master/kusto-syntax-highlighting#testing

**Comment by RamenTurismo** [comment]
@rosshamish Thanks! Didn't have time to come back to this. 
I'll comment when I find a solution, otherwise someone else can start to grab this issue.

**Comment by rosshamish** [comment]
@RamenTurismo - FYI @golf1052 contributed a change in #85 that has improved the color theme compatibility somewhat. They included some generated screenshots in different themes if you're interested. They're in the test/snapshots directory here: https://github.com/rosshamish/kuskus/tree/master/kusto-syntax-highlighting/test/snapshots/create-or-alter-function/theme-visuals

**Comment by rosshamish** [comment]
Closing for now. Feel free to reopen if #85 did not address your concerns here.
