### ISSUE TITLE
[Feature Request] Markdown Syntax Highlighting Support

### ISSUE THREAD

**Issue by mikepeterson-ms** [rosshamish/kuskus#93]
# [Feature Request] Markdown Syntax Highlighting Support

## Reproduction

For those that don't know, when you create a codeblock in a VSCode markdown document, you can put many well-known languages on the same line, and it will provide syntax highlighting. Copy/paste the following in a VSCode markdown documen to see what I mean.
~~~
```Python
# Python comment
print("Hellow World")
```
~~~

"Python" and "py" provide syntax.

"Golang" and "Go" uses different comment blocks, just to illustrate that it is language specific

~~~
```Golang
package main
import ("fmt")

func main() {
  // This is a comment
  fmt.Println("Hello World!")
}
```
~~~

However, with KQL/Kusto, it has no syntax highlighting, and defaults to the standard codeblock.

~~~
```Kusto
// This is a kusto comment 
someTableName
| search "HelloWorld"
```
~~~

## Request
I'm not sure if it's possible to add this feature via kuskus, or if it would have to be added to the default Markdown package (or somewhere else). 

If it can't be added, but you have any other information about where or how a user might manually wedge in their own markdown language support, I would appreciate anything you have to offer.

**Comment by rosshamish** [comment]
I also would love this feature but I also don't know how this is implemented. I encourage you (or anyone reading this) to investigate how codeblock language support is contributed to markdown or gh-flavored markdown. Would be a fantastic contribution.
